name: Python tests

on: push

jobs:
  pytest:
    runs-on: self-hosted
    env:
      PIP_ROOT_USER_ACTION: ignore

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13.2
      uses: actions/setup-python@v5
      with:
        python-version: "3.13.2"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run tests
      run: pytest -vv tests
      working-directory: ${{github.workspace}}
